#!/usr/bin/env python3
"""Render per-lab cluster-setup AsciiDoc blocks from feature-matrix.yml +
cluster/feature-overlays.yml into the home hub partial lab-setup-blocks.adoc.

Consumed by the home hub "Cluster setup" page (include::partial$lab-setup-blocks.adoc[]).
Regenerate after editing feature-overlays.yml: make -C cluster lab-blocks.
"""

import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
MATRIX = REPO / "feature-matrix.yml"
OVERLAYS = Path(__file__).resolve().parent / "feature-overlays.yml"
OUT = REPO / "home" / "content" / "modules" / "ROOT" / "partials" / "lab-setup-blocks.adoc"

BASE_APPLY = (
    "oc apply --server-side --force-conflicts --field-manager=kustomize-base -k cluster/base",
    "make -C cluster wait-csv NS=redhat-ods-operator PREFIX=rhods-operator",
    "make -C cluster dashboard-flags",
)

TWO_STEP = {
    "gpu-config": [
        "make -C cluster wait-csv NS=openshift-nfd PREFIX=nfd",
        "oc apply -k cluster/overlays/gpu-config/activation",
    ],
    "llmd": [
        "make -C cluster wait-csv NS=openshift-lws-operator PREFIX=leader-worker-set",
        "make -C cluster wait-csv NS=openshift-jobset-operator PREFIX=jobset",
        "oc apply -k cluster/overlays/llmd/activation",
    ],
    "gateway": [
        "make -C cluster wait-csv NS=openshift-operators PREFIX=rhcl",
        "oc apply -k cluster/overlays/gateway/activation",
    ],
}

ENVSUBST = {
    "llmd": "oc kustomize cluster/overlays/llmd | envsubst '${CLUSTER_DOMAIN}' | "
    "oc apply --server-side --force-conflicts --field-manager=kustomize-llmd -f -",
    "maas": "oc kustomize cluster/overlays/maas | envsubst '${CLUSTER_DOMAIN}' | "
    "oc apply --server-side --force-conflicts --field-manager=kustomize-maas -f -",
}

CLUSTER_DOMAIN_EXPORT = "export CLUSTER_DOMAIN=$(oc get ingress.config cluster -o jsonpath='{.spec.domain}')"


def overlay_commands(name, spec):
    cmds = []
    if name in ENVSUBST:
        cmds.append(ENVSUBST[name])
    else:
        cmds.append(
            f"oc apply --server-side --force-conflicts --field-manager=kustomize-{name} "
            f"-k cluster/overlays/{name}"
        )
    if spec.get("two_step"):
        cmds.extend(TWO_STEP[name])
    return cmds


def lab_commands(overlays, overlay_specs, order_index, base_only_note=None):
    """Emit the full command list for one lab: base + overlays (deps first) + verify."""
    cmds = list(BASE_APPLY)
    if base_only_note:
        cmds.insert(0, f"# {base_only_note}")
    needs_domain = any(o in ENVSUBST for o in overlays)
    domain_exported = False
    for name in sorted(overlays, key=lambda o: order_index[o]):
        if needs_domain and not domain_exported:
            cmds.append(CLUSTER_DOMAIN_EXPORT)
            domain_exported = True
        cmds.extend(overlay_commands(name, overlay_specs[name]))
        if name == "maas":
            cmds.append("# no-LB clusters (RHDP/bare-metal): make -C cluster gateway-status")
    cmds.append("make -C cluster cluster-verify")
    return cmds


def render_block(title, subtitle, cmds):
    lines = [f".{title} (`{subtitle}`)", "[%collapsible]", "====", "[source,bash,role=\"execute\"]", "----"]
    lines.extend(cmds)
    lines.extend(["----", "====", ""])
    return lines


def main():
    matrix = yaml.safe_load(MATRIX.read_text())
    overlays_cfg = yaml.safe_load(OVERLAYS.read_text())

    overlay_specs = overlays_cfg["overlays"]
    order_index = {name: i for i, name in enumerate(overlays_cfg["apply_order"])}
    feature_map = overlays_cfg.get("features", {})

    known_slugs = {f["slug"] for cat in matrix["categories"] for f in cat["features"]}
    for slug in feature_map:
        if slug not in known_slugs:
            print(f"warning: feature-overlays.yml lab '{slug}' not in feature-matrix.yml — skipped", file=sys.stderr)

    out = [
        "// GENERATED by cluster/gen-lab-setups.py — do not edit.",
        "// Regenerate: make -C cluster lab-blocks",
        "",
    ]
    for cat in matrix["categories"]:
        out.append(f"== {cat['name']}")
        out.append("")
        for feature in cat["features"]:
            slug = feature["slug"]
            name = feature["name"]
            raw = list(feature_map.get(slug, []))
            if slug not in feature_map:
                print(f"warning: lab '{slug}' missing from feature-overlays.yml — emitted as base-only", file=sys.stderr)
                raw = []
            overlays = [o for o in raw if o != "oidc"]
            if not overlays:
                note = "base only (no overlays beyond base for this lab)"
                if raw == ["oidc"]:
                    note = "oidc is a base-only no-op; OCP direct-OIDC is install-time config"
                out.extend(render_block(name, slug, lab_commands([], overlay_specs, order_index, note)))
            else:
                out.extend(render_block(name, slug, lab_commands(overlays, overlay_specs, order_index)))

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
